# Generated by Django 6.0.1 on 2026-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('phone_no', models.CharField(blank=True, max_length=12, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
